# Generated by Django 2.2.4 on 2019-08-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10)),
                ('work_experience', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('emailContact', models.CharField(default='', max_length=100)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(blank=True, max_length=100)),
                ('skill4', models.CharField(blank=True, max_length=100)),
                ('about_me', models.TextField()),
                ('images', models.ImageField(default='default.jpg', upload_to='employeeProfiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobsapp.User')),
            ],
        ),
    ]
